# Copyright 2020 Google LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Service
metadata:
  labels:
    service: web
  name: ecomm
  namespace: monolith
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 8080
  selector:
    service: web
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: web
  name: ecomm
  namespace: monolith
spec:
  replicas: 1
  selector:
    matchLabels:
      service: web
  template:
    metadata:
      labels:
        service: web
    spec:
      containers:
      - name: ecomm
        env:
        - name: DB_HOST
          value:  [DB_IP]:3306
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dbsecret
              key: password
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: dbsecret
              key: username
        image: gcr.io/[PROJECT_ID]/ecomm
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
