# Copyright 2020 Google LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto

import sys
_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name='demo.proto',
    package='',
    syntax='proto3',
    serialized_options=_b('\n\034demo.microservices.sync.grpcP\001'),
    serialized_pb=_b(
        '\n\ndemo.proto\x1a\x1bgoogle/protobuf/empty.proto\"2\n\x16RecommendationsRequest\x12\x18\n\x10product_category\x18\x01 \x03(\t\"2\n\x1bListRecommendationsResponse\x12\x13\n\x0bproduct_ids\x18\x01 \x03(\t\"&\n\x14HealthStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xa7\x01\n\x15RecommendationService\x12N\n\x13ListRecommendations\x12\x17.RecommendationsRequest\x1a\x1c.ListRecommendationsResponse\"\x00\x12>\n\x0bHealthCheck\x12\x16.google.protobuf.Empty\x1a\x15.HealthStatusResponse\"\x00\x42 \n\x1c\x64\x65mo.microservices.sync.grpcP\x01\x62\x06proto3'
    ),
    dependencies=[
        google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,
    ])

_RECOMMENDATIONSREQUEST = _descriptor.Descriptor(
    name='RecommendationsRequest',
    full_name='RecommendationsRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='product_category',
            full_name='RecommendationsRequest.product_category',
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=43,
    serialized_end=93,
)

_LISTRECOMMENDATIONSRESPONSE = _descriptor.Descriptor(
    name='ListRecommendationsResponse',
    full_name='ListRecommendationsResponse',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='product_ids',
            full_name='ListRecommendationsResponse.product_ids',
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=95,
    serialized_end=145,
)

_HEALTHSTATUSRESPONSE = _descriptor.Descriptor(
    name='HealthStatusResponse',
    full_name='HealthStatusResponse',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='status',
            full_name='HealthStatusResponse.status',
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b('').decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=147,
    serialized_end=185,
)

DESCRIPTOR.message_types_by_name[
    'RecommendationsRequest'] = _RECOMMENDATIONSREQUEST
DESCRIPTOR.message_types_by_name[
    'ListRecommendationsResponse'] = _LISTRECOMMENDATIONSRESPONSE
DESCRIPTOR.message_types_by_name['HealthStatusResponse'] = _HEALTHSTATUSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecommendationsRequest = _reflection.GeneratedProtocolMessageType(
    'RecommendationsRequest',
    (_message.Message,),
    {
        'DESCRIPTOR': _RECOMMENDATIONSREQUEST,
        '__module__': 'demo_pb2'
        # @@protoc_insertion_point(class_scope:RecommendationsRequest)
    })
_sym_db.RegisterMessage(RecommendationsRequest)

ListRecommendationsResponse = _reflection.GeneratedProtocolMessageType(
    'ListRecommendationsResponse',
    (_message.Message,),
    {
        'DESCRIPTOR': _LISTRECOMMENDATIONSRESPONSE,
        '__module__': 'demo_pb2'
        # @@protoc_insertion_point(class_scope:ListRecommendationsResponse)
    })
_sym_db.RegisterMessage(ListRecommendationsResponse)

HealthStatusResponse = _reflection.GeneratedProtocolMessageType(
    'HealthStatusResponse',
    (_message.Message,),
    {
        'DESCRIPTOR': _HEALTHSTATUSRESPONSE,
        '__module__': 'demo_pb2'
        # @@protoc_insertion_point(class_scope:HealthStatusResponse)
    })
_sym_db.RegisterMessage(HealthStatusResponse)

DESCRIPTOR._options = None

_RECOMMENDATIONSERVICE = _descriptor.ServiceDescriptor(
    name='RecommendationService',
    full_name='RecommendationService',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=188,
    serialized_end=355,
    methods=[
        _descriptor.MethodDescriptor(
            name='ListRecommendations',
            full_name='RecommendationService.ListRecommendations',
            index=0,
            containing_service=None,
            input_type=_RECOMMENDATIONSREQUEST,
            output_type=_LISTRECOMMENDATIONSRESPONSE,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name='HealthCheck',
            full_name='RecommendationService.HealthCheck',
            index=1,
            containing_service=None,
            input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
            output_type=_HEALTHSTATUSRESPONSE,
            serialized_options=None,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_RECOMMENDATIONSERVICE)

DESCRIPTOR.services_by_name['RecommendationService'] = _RECOMMENDATIONSERVICE

# @@protoc_insertion_point(module_scope)
